### PR TITLE
Issue #4 - Support numeric splits for categorical features

### PR DESCRIPTION
**Pull request by eblood66**
Speaks to #4

We recently wanted to use the jpmml-h2o converter for a large H2O tree model and ran into this issue.  This patch worked for our model and for the synthetic model I created for the test case here.

### CODE REVIEW

**Comment by vruusmann** [comment]
Two questions:

1. Is this PR likely related (a fix) to https://github.com/jpmml/jpmml-h2o/issues/4
2. How was the "DecisionTreeSplitCat" model trained? By simply applying `H2ORandomForestEstimator(ntrees = 1)` estimator to the "SplitCat" dataset? Or something else?

I'd like to have a Python script for (re-)generating the "DecisionTreeSplitCat" model from scratch, which I could (re-)run when upgrading/updating H2O.ai version.

All other models have their "source code" here: https://github.com/jpmml/jpmml-h2o/blob/master/pmml-h2o/src/test/resources/main.py

**Comment by eblood66** [comment]
1. Yes, it's a fix for #4.
2. It was trained using the H2O UI, with a random distributed forest model with ntrees=5 and ncat_bins=256 on the SplitCat dataset with a Score added.

I didn't see the main.py script.  I'll look to add this model to it and add the Score field back to SplitCat so it can be used for training as well.

**Comment by vruusmann** [comment]
The H2O.ai hyperparameter that triggers this (currently unsupported-) behaviour appears to be called `nbins_cats` (not `ncat_bins`): https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/nbins_cats.html

**Comment by eblood66** [comment]
Yes, sorry.  I was going off memory.  I should have looked it up first.

**Comment by eblood66** [comment]
Excellent.  Would you like me to make any changes to the PR or do you want to take care of it yourself?  Just let me know.

**Comment by vruusmann** [comment]
I'm researching and fixing this issue myself, now that I have access to misbehaving models.

**Comment by vruusmann** [comment]
I noticed an additional code change in this PR, which appears to address a separate issue.

Specifically, I have the left-vs-right decision coded here:
https://github.com/jpmml/jpmml-h2o/blob/4f50e83ab267ab6c2b94c8c725290f7942d9d5e6/pmml-h2o/src/main/java/org/jpmml/h2o/SharedTreeMojoModelConverter.java#L237-L243

But in the patchfile, the decisioning logic appears to account for a possibility that category value indices exceed bitset's size:
```java
if ((bitSet.isInRange(i) && !bitSet.contains(i) || (!bitSet.isInRange(i) && leftward))) {
	leftValues.add(value);
} else {
	rightValues.add(value);
}
```

In PMML speak, it corresponds to the handling of "invalid values".

Is there any explanation why this code change was added? Some H2O.ai hyperparameter, that allows for invalid values (ie. values not seen in the training dataset) to be predicted?

My fix to #16 currently does not include this code change. If it's needed, then it should be added separately.

**Comment by eblood66** [comment]
It is necessary to match H2O with the synthetic dataset I was using.  This did not involve any invalid values, only values from the training set.

It looks like H2O uses a bit offset to reduce the size of the bitset in some cases (but only when the bitset size is over 32 bits).  For bitsets with a bit offset, the bits before the offset are still valid categorical items and they are assumed to go to the left or right based on the leftward node option.  At least that's how it looks.   I didn't find the code in H2O which includes this logic for model generation but the POJO evaluator for the model does include this logic.

Attached is the training data I used to create the model where this shows up:

[DecisionTreeSplitCat_training.csv](https://github.com/user-attachments/files/16715486/DecisionTreeSplitCat_training.csv)

**Comment by vruusmann** [comment]
> It looks like H2O uses a bit offset to reduce the size of the bitset in some cases (but only when the bitset size is over 32 bits).

Sounds very intuitive.

However, I can't reproduce the need for finer BitSet handling using the synthetic dataset (the provided one, and another one that I generated using Scikit-Learn's `make_regression` utility function).

Also, the `DecisionTreeSplitCat.zip` file that is attached here doesn't seem to need it - converts fine using the current HEAD version.

**Comment by eblood66** [comment]
I'm not sure why you couldn't duplicate it with my DecisionTreeSplitCat.zip model.  When I run it with the current HEAD I get conflicts.  

However, I put together a model generated by the attached main.py which triggers the problem.  When run using the also attached `evaluateBitOff` test, I get the following when assertions are enabled:

````
java.lang.AssertionError: Must have 330 <= idx <= 497: 168

	at hex.genmodel.utils.GenmodelBitSet.contains(GenmodelBitSet.java:52)
	at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:237)
	at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:341)
	at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:303)
	at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeNode(SharedTreeMojoModelConverter.java:303)
	at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeTreeModel(SharedTreeMojoModelConverter.java:150)
	at org.jpmml.h2o.SharedTreeMojoModelConverter.encodeTreeModels(SharedTreeMojoModelConverter.java:115)
	at org.jpmml.h2o.DrfMojoModelConverter.encodeModel(DrfMojoModelConverter.java:59)
	at org.jpmml.h2o.Converter.encodePMML(Converter.java:87)
	at org.jpmml.h2o.testing.H2OEncoderBatch.getPMML(H2OEncoderBatch.java:60)
	at org.jpmml.converter.testing.ModelEncoderBatch.getEvaluatorBuilder(ModelEncoderBatch.java:124)
	at org.jpmml.converter.testing.ModelEncoderBatch.getEvaluator(ModelEncoderBatch.java:114)
	at org.jpmml.evaluator.testing.BatchUtil.evaluate(BatchUtil.java:45)
	at org.jpmml.evaluator.testing.BatchTest.evaluate(BatchTest.java:35)
	at org.jpmml.converter.testing.ModelEncoderBatchTest.evaluate(ModelEncoderBatchTest.java:52)
	at org.jpmml.converter.testing.ModelEncoderBatchTest.evaluate(ModelEncoderBatchTest.java:37)
	at org.jpmml.evaluator.testing.ArchiveBatchTest.evaluate(ArchiveBatchTest.java:63)
	at org.jpmml.evaluator.testing.ArchiveBatchTest.evaluate(ArchiveBatchTest.java:41)
	at org.jpmml.h2o.testing.DrfMojoModelConverterTest.evaluateBitOff(DrfMojoModelConverterTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
````

With assertions disabled I get:

````
Conflict{id=296, arguments={Code=C297, Score=0}, differing (expected vs. actual)={Score=(0.2, {result=0.0})}}
Conflict{id=297, arguments={Code=C298, Score=0}, differing (expected vs. actual)={Score=(0.2, {result=0.0})}}
Conflict{id=601, arguments={Code=C602, Score=0}, differing (expected vs. actual)={Score=(0.2, {result=0.0})}}
Conflict{id=602, arguments={Code=C603, Score=0}, differing (expected vs. actual)={Score=(0.2, {result=0.0})}}
Conflict{id=603, arguments={Code=C604, Score=0}, differing (expected vs. actual)={Score=(0.4, {result=0.2})}}

java.lang.AssertionError: Found 5 conflict(s)

	at org.junit.Assert.fail(Assert.java:89)
	at org.jpmml.evaluator.testing.BatchTest.evaluate(BatchTest.java:43)
	at org.jpmml.converter.testing.ModelEncoderBatchTest.evaluate(ModelEncoderBatchTest.java:52)
	at org.jpmml.converter.testing.ModelEncoderBatchTest.evaluate(ModelEncoderBatchTest.java:37)
	at org.jpmml.evaluator.testing.ArchiveBatchTest.evaluate(ArchiveBatchTest.java:63)
	at org.jpmml.evaluator.testing.ArchiveBatchTest.evaluate(ArchiveBatchTest.java:41)
	at org.jpmml.h2o.testing.DrfMojoModelConverterTest.evaluateBitOff(DrfMojoModelConverterTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
````
[BitOffsetIssue.zip](https://github.com/user-attachments/files/16732577/BitOffsetIssue.zip)

**Comment by vruusmann** [comment]
> I'm not sure why you couldn't duplicate it with my DecisionTreeSplitCat.zip model. When I run it with the current HEAD I get conflicts.

I'm using the `DecisionTreeSplitCat.zip` file, which is downloaded from this PR:

```
$ md5sum DecisionTreeSplitCat.zip 
fd17fb813f360f6130af1fbc8c1ca390  DecisionTreeSplitCat.zip
```

And then:

```
$ java -jar pmml-h2o-example/target/pmml-h2o-example-executable-1.2-SNAPSHOT.jar --mojo-input DecisionTreeSplitCat.zip --pmml-output DecisionTreeSplitCat.pmml
aug 23, 2024 10:15:07 PM org.jpmml.h2o.example.Main run
INFO: Loading MOJO..
aug 23, 2024 10:15:07 PM org.jpmml.h2o.example.Main run
INFO: Loaded MOJO in 125 ms.
aug 23, 2024 10:15:07 PM org.jpmml.h2o.example.Main run
INFO: Converting MOJO to PMML..
aug 23, 2024 10:15:08 PM org.jpmml.h2o.example.Main run
INFO: Converted MOJO to PMML in 362 ms.
aug 23, 2024 10:15:08 PM org.jpmml.h2o.example.Main run
INFO: Marshalling PMML..
aug 23, 2024 10:15:09 PM org.jpmml.h2o.example.Main run
INFO: Marshalled PMML in 1040 ms.
```

But I appreciate your efforts in trying to exemplify this BitSet offset thing. I'd like to study it and then integrate it into the upcoming JPMML-H2O release.

**Pull request closed without merging**
